// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ems_backend.Data.DataContext;

#nullable disable

namespace ems_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240723024442_createdb")]
    partial class createdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ems_backend.Models.Entities.CapPhatTaiSan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("NgayCapPhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTraLai")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<int>("TaiSanId")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.HasIndex("TaiSanId");

                    b.ToTable("CapPhatTaiSans");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.ChiNhanhNganHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NganHangId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChiNhanhNganHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NganHangId");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("ChiNhanhNganHangs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.ChucDanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenChucDanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("ChucDanhs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.ChucDanhPhongBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChucDanhId")
                        .HasColumnType("int");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChucDanhId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("ChucDanhPhongBans");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.DanhMucKhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenThamSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("DanhMucKhacs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.HopDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ChiTietHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoSoLuongId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiHopDongId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<int>("QuyetDinhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoSoLuongId");

                    b.HasIndex("LoaiHopDongId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.HoSoLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BacLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChucDanhPhongBanId")
                        .HasColumnType("int");

                    b.Property<decimal>("LuongMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LuongMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<string>("ThangLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChucDanhPhongBanId");

                    b.HasIndex("NhanVienId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("HoSoLuongs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.HoSoLuong_PhuCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HoSoLuongId")
                        .HasColumnType("int");

                    b.Property<int>("PhuCapId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HoSoLuongId");

                    b.HasIndex("PhuCapId");

                    b.ToTable("HoSoLuong_PhuCaps");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.HoSoLuong_PhucLoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HoSoLuongId")
                        .HasColumnType("int");

                    b.Property<int>("PhucLoiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoSoLuongId");

                    b.HasIndex("PhucLoiId");

                    b.ToTable("HoSoLuong_PhucLois");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.KhenThuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LoaiKhenThuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKhenThuong")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("KhenThuongs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.KyLuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LoaiKyLuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKyLuat")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("KyLuats");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.LoaiHopDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("LoaiHopDongs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NganHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("NganHangs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NghiViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNghiViec")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("NghiViecs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NguoiThanNhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("GiamTruGiaCanh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayBatDauGiaGiam")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("QuanHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiThan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("NguoiThanNhanViens");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ChiNhanhNganHangId")
                        .HasColumnType("int");

                    b.Property<int?>("ChucDanhPhongBanId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NganHangId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<int?>("NoiKhamBenhId")
                        .HasColumnType("int");

                    b.Property<int?>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<int?>("QuanHuyenId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TinhThanhId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("XaPhuongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChiNhanhNganHangId");

                    b.HasIndex("ChucDanhPhongBanId");

                    b.HasIndex("NganHangId");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("NoiKhamBenhId");

                    b.HasIndex("PhongBanId");

                    b.HasIndex("QuanHuyenId");

                    b.HasIndex("TinhThanhId");

                    b.HasIndex("XaPhuongId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NoiKhamBenh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNoiKhamBenh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("NoiKhamBenhs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.PhongBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("PhongBans");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.PhuCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenPhuCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("PhuCaps");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.PhucLoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenPhucLoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("PhucLois");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.QuanHuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenQuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TinhThanhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("TinhThanhId");

                    b.ToTable("QuanHuyens");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.QuyetDinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("HoSoLuongId")
                        .HasColumnType("int");

                    b.Property<int>("HopDongId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HoSoLuongId");

                    b.HasIndex("HopDongId")
                        .IsUnique();

                    b.HasIndex("NhanVienId");

                    b.ToTable("QuyetDinhs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.TaiSan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenTaiSan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("TaiSans");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.TapTinDinhKem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("TenTapTin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("TapTinDinhKems");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.TinhThanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("TinhThanhs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.XaPhuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<int>("QuanHuyenId")
                        .HasColumnType("int");

                    b.Property<string>("TenXaPhuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiCapNhatId");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("QuanHuyenId");

                    b.ToTable("XaPhuongs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.CapPhatTaiSan", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("CapPhatTaiSans")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.TaiSan", "TaiSan")
                        .WithMany("CapPhatTaiSans")
                        .HasForeignKey("TaiSanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("TaiSan");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.ChiNhanhNganHang", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NganHang", "NganHang")
                        .WithMany("ChiNhanhNganHangs")
                        .HasForeignKey("NganHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NganHang");

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.ChucDanh", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.ChucDanhPhongBan", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.ChucDanh", "ChucDanh")
                        .WithMany("ChucDanhPhongBans")
                        .HasForeignKey("ChucDanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.PhongBan", "PhongBan")
                        .WithMany("ChucDanhPhongBans")
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucDanh");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.DanhMucKhac", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.HopDong", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.HoSoLuong", "HoSoLuong")
                        .WithMany("HopDongs")
                        .HasForeignKey("HoSoLuongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.LoaiHopDong", "LoaiHopDong")
                        .WithMany("HopDongs")
                        .HasForeignKey("LoaiHopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("HopDongs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoLuong");

                    b.Navigation("LoaiHopDong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.HoSoLuong", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.ChucDanhPhongBan", "ChucDanhPhongBan")
                        .WithMany()
                        .HasForeignKey("ChucDanhPhongBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("HoSoLuongs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.PhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucDanhPhongBan");

                    b.Navigation("NhanVien");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.HoSoLuong_PhuCap", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.HoSoLuong", "HoSoLuong")
                        .WithMany("HoSoLuongPhuCaps")
                        .HasForeignKey("HoSoLuongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.PhuCap", "PhuCap")
                        .WithMany("HoSoLuongPhuCaps")
                        .HasForeignKey("PhuCapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoLuong");

                    b.Navigation("PhuCap");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.HoSoLuong_PhucLoi", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.HoSoLuong", "HoSoLuong")
                        .WithMany("HoSoLuongPhucLois")
                        .HasForeignKey("HoSoLuongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.PhucLoi", "PhucLoi")
                        .WithMany("HoSoLuongPhucLois")
                        .HasForeignKey("PhucLoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoLuong");

                    b.Navigation("PhucLoi");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.KhenThuong", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("KhenThuongs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.KyLuat", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("KyLuats")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.LoaiHopDong", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NganHang", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NghiViec", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("NghiViecs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NguoiThanNhanVien", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("NguoiThanNhanViens")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NhanVien", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.ChiNhanhNganHang", "ChiNhanhNganHang")
                        .WithMany("NhanViens")
                        .HasForeignKey("ChiNhanhNganHangId");

                    b.HasOne("ems_backend.Models.Entities.ChucDanhPhongBan", "ChucDanhPhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("ChucDanhPhongBanId");

                    b.HasOne("ems_backend.Models.Entities.NganHang", "NganHang")
                        .WithMany("NhanViens")
                        .HasForeignKey("NganHangId");

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ems_backend.Models.Entities.NoiKhamBenh", "NoiKhamBenh")
                        .WithMany("NhanViens")
                        .HasForeignKey("NoiKhamBenhId");

                    b.HasOne("ems_backend.Models.Entities.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("PhongBanId");

                    b.HasOne("ems_backend.Models.Entities.QuanHuyen", "QuanHuyen")
                        .WithMany("NhanVien")
                        .HasForeignKey("QuanHuyenId");

                    b.HasOne("ems_backend.Models.Entities.TinhThanh", "TinhThanh")
                        .WithMany("NhanViens")
                        .HasForeignKey("TinhThanhId");

                    b.HasOne("ems_backend.Models.Entities.XaPhuong", "XaPhuong")
                        .WithMany("NhanViens")
                        .HasForeignKey("XaPhuongId");

                    b.Navigation("ChiNhanhNganHang");

                    b.Navigation("ChucDanhPhongBan");

                    b.Navigation("NganHang");

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");

                    b.Navigation("NoiKhamBenh");

                    b.Navigation("PhongBan");

                    b.Navigation("QuanHuyen");

                    b.Navigation("TinhThanh");

                    b.Navigation("XaPhuong");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NoiKhamBenh", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.PhongBan", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.PhuCap", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.PhucLoi", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.QuanHuyen", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.TinhThanh", "TinhThanh")
                        .WithMany("QuanHuyens")
                        .HasForeignKey("TinhThanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.QuyetDinh", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.HoSoLuong", "HoSoLuong")
                        .WithMany()
                        .HasForeignKey("HoSoLuongId");

                    b.HasOne("ems_backend.Models.Entities.HopDong", "HopDong")
                        .WithOne("QuyetDinh")
                        .HasForeignKey("ems_backend.Models.Entities.QuyetDinh", "HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("QuyetDinhs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoLuong");

                    b.Navigation("HopDong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.TaiSan", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.TapTinDinhKem", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NhanVien")
                        .WithMany("TapTinDinhKems")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.TinhThanh", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.XaPhuong", b =>
                {
                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.NhanVien", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ems_backend.Models.Entities.QuanHuyen", "QuanHuyen")
                        .WithMany("XaPhuongs")
                        .HasForeignKey("QuanHuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiCapNhat");

                    b.Navigation("NguoiTao");

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.ChiNhanhNganHang", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.ChucDanh", b =>
                {
                    b.Navigation("ChucDanhPhongBans");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.ChucDanhPhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.HopDong", b =>
                {
                    b.Navigation("QuyetDinh");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.HoSoLuong", b =>
                {
                    b.Navigation("HoSoLuongPhuCaps");

                    b.Navigation("HoSoLuongPhucLois");

                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.LoaiHopDong", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NganHang", b =>
                {
                    b.Navigation("ChiNhanhNganHangs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NhanVien", b =>
                {
                    b.Navigation("CapPhatTaiSans");

                    b.Navigation("HoSoLuongs");

                    b.Navigation("HopDongs");

                    b.Navigation("KhenThuongs");

                    b.Navigation("KyLuats");

                    b.Navigation("NghiViecs");

                    b.Navigation("NguoiThanNhanViens");

                    b.Navigation("QuyetDinhs");

                    b.Navigation("TapTinDinhKems");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.NoiKhamBenh", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.PhongBan", b =>
                {
                    b.Navigation("ChucDanhPhongBans");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.PhuCap", b =>
                {
                    b.Navigation("HoSoLuongPhuCaps");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.PhucLoi", b =>
                {
                    b.Navigation("HoSoLuongPhucLois");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.QuanHuyen", b =>
                {
                    b.Navigation("NhanVien");

                    b.Navigation("XaPhuongs");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.TaiSan", b =>
                {
                    b.Navigation("CapPhatTaiSans");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.TinhThanh", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("QuanHuyens");
                });

            modelBuilder.Entity("ems_backend.Models.Entities.XaPhuong", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
